name: Test and Package

on:
  push:
    branches: [ master, main, 'feature/**' ]
    tags:
      - 'v*'  # Trigger on version tags like v2.0, v2.1.0, etc.
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  test-and-package:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        php-version: ['7.4', '8.1']
    
    name: PHP ${{ matrix.php-version }} Test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        coverage: none
        tools: composer:v2
    
    - name: Check PHP Version
      run: php -v
    
    - name: Run tests
      run: make test
    
    - name: Quick Plugin Check
      if: matrix.php-version == '8.1'  # Only run plugin check once
      run: |
        echo "Running basic plugin validation..."
        # Check that required files exist
        test -f goalietron.php || { echo "Missing main plugin file"; exit 1; }
        test -f readme.txt || { echo "Missing readme.txt"; exit 1; }
        test -f LICENSE || { echo "Missing LICENSE file"; exit 1; }
        
        # Check plugin header
        grep -q "Plugin Name:" goalietron.php || { echo "Missing Plugin Name header"; exit 1; }
        grep -q "License:" goalietron.php || { echo "Missing License header"; exit 1; }
        
        echo "✓ Basic plugin structure validation passed"
    
    - name: Create plugin package
      if: matrix.php-version == '8.1'  # Only create package once
      run: make package
    
    - name: Upload plugin package
      if: matrix.php-version == '8.1'  # Only upload from one PHP version
      uses: actions/upload-artifact@v4
      with:
        name: goalietron-plugin-${{ github.sha }}
        path: goalietron-plugin.zip
        retention-days: 30
    
    - name: Upload test results
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-php${{ matrix.php-version }}
        path: tests/*.log
        retention-days: 7

  release-package:
    needs: test-and-package
    runs-on: ubuntu-latest
    if: success() && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/'))
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
    
    - name: Create release package
      run: |
        make package
        VERSION=$(grep "Version:" goalietron.php | sed 's/.*Version: //')
        mv goalietron-plugin.zip goalietron-v${VERSION}.zip
        echo "PLUGIN_VERSION=${VERSION}" >> $GITHUB_ENV
        echo "PLUGIN_FILE=goalietron-v${VERSION}.zip" >> $GITHUB_ENV
    
    - name: Upload release artifact
      uses: actions/upload-artifact@v4
      with:
        name: goalietron-release-${{ github.sha }}
        path: goalietron-v*.zip
        retention-days: 90
    
    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ env.PLUGIN_FILE }}
        name: GoalieTron v${{ env.PLUGIN_VERSION }}
        body: |
          ## GoalieTron v${{ env.PLUGIN_VERSION }}
          
          WordPress plugin for displaying Patreon goals and pledge progress.
          
          ### Installation
          1. Download `${{ env.PLUGIN_FILE }}` from the assets below
          2. Upload to your WordPress plugins directory
          3. Activate the plugin
          4. Add the GoalieTron block to your site
          
          ### Changelog
          See [CHANGELOG.md](https://github.com/partouf/GoalieTron/blob/master/CHANGELOG.md) for details.
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}